Page setup
Zubenna/youtube-clone pull request #1
Opened 2020-02-24 22:55 UTC by 3rkeen

2020-02-24 23:15 UTC, addod19 commented
## Hi Team,
Your project will be marked as invalid because of the following reason:
- The project has no descriptive PR. PR must have a title and a short description.

- The project has no professional** README**  file

2020-02-25 17:15 UTC, Zubenna commented
Created layout for the webpage

2020-02-25 18:02 UTC, mosesogwo requested changes
**HI @3rkeen, @Zubenna. Good job on your first project:clap:. Let's now take care of the following :arrow_forward:**

1. Reduce the font-size of video titles in the recommended videos side bar to enable the rest of the information fit within the video height.
**Original:**
![image](https://user-images.githubusercontent.com/46611870/75272950-28bd6800-57ff-11ea-84d3-83ecff7c8826.png)

**Yours:**
![image](https://user-images.githubusercontent.com/46611870/75272984-370b8400-57ff-11ea-87be-943848ca39fe.png)

2. Position the subscribe button properly

3. Remove all inline stylings from your html

4. You have a single warning from the html validation. You could add a header to that section and set it s display property to none.

5. You should generate a live link for your page at https://raw.githack.com and include it in your readme.

6. Author 1 Information in the readme have no links. There should be links to the various platforms identified.

7. Use hyperlinks for links in your readme to keep it neat. Consider using the Microverse template provided [here](https://github.com/microverseinc/readme-template)

_**Kindly address the above and submit another code review request. Note that you don't have to open another pull request.**_

**Cheers:stars:**

2020-02-25 20:49 UTC, mosesogwo requested changes
**Hello, we haven't made all the changes from the previous review yet:**

1. The subscribe button is not properly placed. It should fall in line with the author avatar.
**Yours:** 
![image](https://user-images.githubusercontent.com/46611870/75286159-49de8280-5818-11ea-9548-37b589224fdf.png)

**Original:**
![image](https://user-images.githubusercontent.com/46611870/75286181-52cf5400-5818-11ea-973c-30caa2a372cc.png)

2. You still have one inline style in your html. See line 51 of your index.html

_**Please fix them and submit another code review request. You're almost there :muscle:**_

2020-02-25 20:49 UTC, mosesogwo commented on index.html
> +            <p style="font-size: small;">6,636,870,358 views • Jan 13, 2017</p>
Move this style into the css

2020-02-25 22:15 UTC, mosesogwo approved these changes
**You have done well implementing the changes:+1: Your project is now approved!:heavy_check_mark:**

You can now merge to master.

**Good luck in your next project:stars:**

2020-02-25 22:33 UTC, merged